from typing import Protocol, Optional, List
from core.entities.task import Task, TaskType, TaskStatus, TaskPriority
from core.entities.agent import Agent, AgentRole


class TaskRepository(Protocol):
    def save(self, task: Task) -> int: ...
    def get(self, task_id: int) -> Optional[Task]: ...
    def update(self, task: Task) -> bool: ...
    def delete(self, task_id: int) -> bool: ...
    def list(self, status: Optional[str] = None, agent: Optional[str] = None, limit: int = 50) -> List[Task]: ...
    def count_by_status(self) -> dict: ...


class AgentRepository(Protocol):
    def save(self, agent: Agent) -> int: ...
    def get(self, agent_id: int) -> Optional[Agent]: ...
    def get_by_role(self, role: AgentRole) -> Optional[Agent]: ...
    def list(self) -> List[Agent]: ...
    def update(self, agent: Agent) -> bool: ...
    def stats(self) -> List[dict]: ...


class AIProvider(Protocol):
    async def analyze(self, prompt: str, system_prompt: str = "") -> str: ...
    async def classify(self, text: str) -> str: ...
    async def health(self) -> bool: ...


class SecurityVault(Protocol):
    def get(self, key: str) -> Optional[str]: ...
    def set(self, key: str, value: str) -> None: ...
    def validate(self) -> dict: ...


class SystemMonitor(Protocol):
    def check_health(self) -> dict: ...
    def record_metric(self, name: str, value: float) -> None: ...
    def get_metrics(self, since: str) -> dict: ...
